version: "3.9"
services: 
    api:
        image: nefcanto/dotnet-dev:latest
        restart: always
        container_name: BlogApi
        working_dir: /BlogApi        
        volumes: 
            - .:/BlogApi
        ports: 
            - "5000:5000"
        command: >
            sh -c
            "
            tail -f /dev/null                       
            "